### ISSUE TITLE
Subclasses are not recognized in 9.4

### ISSUE THREAD

**Issue by bob-hoff** [johnbywater/eventsourcing#295]
Hi,

First of all I want to thank you for providing an amazing library and continuously working on updating it.

I encountered an issue with the latest 9.4 release where subclasses are no longer recognized.

Here is a minimal example where the assert fails in 9.4 but passes in 9.3.

```python
from datetime import datetime
from uuid import UUID

from eventsourcing.domain import CanInitAggregate, CanMutateAggregate
from eventsourcing.domain import Aggregate as BaseAggregate

from pydantic import BaseModel


class DomainEvent(BaseModel):
    originator_id: UUID
    originator_version: int
    timestamp: datetime


class Aggregate(BaseAggregate):
    class Event(DomainEvent, CanMutateAggregate):
        pass

    class Created(Event, CanInitAggregate):
        originator_topic: str


class DomainId(BaseModel):
    system_id: str


class Entity(Aggregate):
    class BaseEvent(Aggregate.Event, DomainId): ...

    class Scheduled(BaseEvent): ...


assert issubclass(
    Entity.Scheduled, Entity.BaseEvent
)  # Would expect this to be true and was the case with version 9.3
```

I must admit that the magic you do in eventsourcing/domain.py `BaseAggregate` `__init_subclass__` is a bit beyond me, but I suspect it is due to these changes.

My use case is that in the `Entity` I have several events with the same fields. I iterate over the list of events I read from the event store and asserting on the Entity.BaseEvent makes the static type checker happy when accessing these common subfields.

How can I work around this or could this be changed in the library?

**Comment by johnbywater** [comment]
Hey @bob-hoff sorry it broke! I will fix this now. Thanks for your nice comments about the library and for providing these details....

**Comment by johnbywater** [comment]
I understand why this is happening....

One thing `__init_subclass__` does is make sure that all event classes (classes which support the `CanMutateAggregate` protocol) on an aggregate class have a common aggregate-specific "base event" class. That's so all event classes and instances can be identified as events of the aggregate, should somebody want or need to do this, for example when processing events.

Another thing `__init_subclass__` does is make sure all event classes resolvable as attributes on an aggregate class will have topics that, when resolved, will lead through the aggregate class to an event class, and not through an aggregate superclass. That's so in future every aggregate class can always be in control of its event definitions, in case they need to be adjusted.

For example, the topic string of `Entity.Event` will end with "Entity.Event" rather than "Aggregate.Event", and the topic of `Entity.Created` will be "...Entity.Created" rather than "...Aggregate.Created". And `Aggregate.Created` will be a subclass of `Aggregate.Event` not just because that's how it was defined on `Aggregate` but also because that's how it was defined by `__init_subclass__` on `Entity`. The two classes `Entity.Event` and `Entity.Created` are also subclasses of `Aggregate.Event` and `Aggregate.Created` respectively.

To accomplish this, firstly the `__init_subclass__` method ensures each aggregate class has a "base event" class called "Event". The name "Event" is just a convention here. You seem to prefer the name "BaseEvent" :-)

But if an aggregate class doesn't itself define an event class called "Event", then one is defined on that aggregate class by `__init_subclass__` and it assumed to be the "base event" class for that aggregate class. Every other event class defined on the aggregate class is then redefined as a subclass of itself and the aggregate's "base event" class. Finally, every event class defined on every base class of the aggregate class is also redefined as a subclass of itself and this "base event" class.

...

In your case, your class `Entity` doesn't itself define an `Event` class, so the library defines one. Then each event class you have defined on `Entity` is redefined as subclasses of itself and this `Entity.Event` class. That means your `Entity.BaseEvent` class is also subclassed. This new `Entity.BaseEvent` class is what is being used in your `issubclass` test.

The reason your `issubclass` test fails is because `Scheduled` is only a subclass of the original `Entity.BaseEvent` class, and not a subclass of the redefined `Entity.BaseEvent` class. The original hierarchy should be respected by the apparent hierarchy after `__init_subclass__` has done its work.

I'm fixing this now, so if an event class `A` is redefined, then any subclasses of `A` that are redefined will have the redefined `A` class included in their bases. Then your test will pass.

I've checked the attribute definitions are respected, so your Pydantic event classes should actually work as expected. Is that correct? It's just the resulting class hierarchy that isn't correct?

In the meantime, the `issubclass` test will pass if you rename `BaseEvent` to `Event`, so that the library uses it as the "base event" class for the aggregate, and doesn't assume your don't have one. That way you will avoid the library redefining your event classes.

By the way, since you are using Pydantic, you don't need to inherit from the library's `Aggregate` class and can instead inherit from the library's new `BaseAggregate` class which will avoid the "refused bequest" of the `dataclass` event classes defined on `Aggregate`. And it will avoid static type checking complaining about things being redefined in "incompatible" ways. Using `BaseAggregate` will be much cleaner, avoiding several static type checking issues, and unnecessary event class definitions. See this example for more details:
https://eventsourcing.readthedocs.io/en/latest/topics/examples/aggregate8.html

**Comment by bob-hoff** [comment]
Thank you for the very comprehensive answer.

Yes, the attribute definitions of `BaseEvent` are respected, so the Pydantic event classes work as expected, just the resulting class hierarchy isn't correct.
Doing the assert against `Entity.Event` instead of `Entity.BaseEvent` kind of works. Similar for overwriting `Event` in the `Entity` instead of adding my own `BaseEvent`.
However I only want to add this `BaseEvent` to some and not all events (in my case `class Created(Aggregate.Created)` does not inherit from `BaseEvent`) and thus overwriting `Entity.Event` myself is creating new problems.

I agree that fixing this in the library to make it respect the initial class hierarchy is the way to go.

_Pydantic_: Thanks for the hint, I have seen that, but I wanted to provide an example that works with 9.3 and fails with 9.4 without any code changes in the example itself.

**Comment by johnbywater** [comment]
I've fixed it in 9d80a260b698d462ae3cba83e365cc8101301bea.

If possible, can you install this version from the GitHub repo and see if it works for you?

`pip install eventsourcing@git+https://github.com/pyeventsourcing/eventsourcing`

**Comment by johnbywater** [comment]
Hey @bob-hoff I've released https://pypi.org/project/eventsourcing/9.4.5/ which should hopefully resolve the problem you described.

There's a test here which represents this issue, and it's passing.
https://github.com/pyeventsourcing/eventsourcing/blob/188436c8a9cb52df4daebf9d378319dfc8b224b3/tests/domain_tests/test_base_aggregate.py#L692

Please update and let me know if this is working for you now?

Thanks for your gratitude, respectfulness and clarity when explaining what was happening.

If you have any other issues, please don't hesitate!

**Comment by bob-hoff** [comment]
Hi @johnbywater,
Thanks a lot for improving this so quickly.

Unfortunately it does not yet fully resolve my specific problem.

The minimum example I gave was a bit too restrictive and my codebase, which is using Generic, it still fails.

Here is a slightly extended example that makes it fail again (but which worked on 9.3)

```python
from datetime import datetime
from typing import Generic, TypeVar
from uuid import UUID

from eventsourcing.domain import CanInitAggregate, CanMutateAggregate
from eventsourcing.domain import BaseAggregate

from pydantic import BaseModel


class DomainEvent(BaseModel):
    originator_id: UUID
    originator_version: int
    timestamp: datetime


class A(BaseAggregate):
    class Event(DomainEvent, CanMutateAggregate):
        pass

    class Created(Event, CanInitAggregate):
        originator_topic: str


class Shared(BaseModel):
    system_id: str


class ExtendedShared(Shared):
    task_id: str


SharedId = TypeVar("SharedId", bound=Shared)


class B(A):
    class Something(A.Event, Generic[SharedId]):
        shared_id: SharedId

    class Else(Something[ExtendedShared]):
        pass

    class Scheduled(Else):
        pass


# Redefined classes should respect original hierarchy.
assert issubclass(B.Scheduled, B.Something)
```

In my specific case, I can work around it, as I do not necessarily need to use Generic. 
However as it is unexpected for the library to change the hierarchy in this way, maybe you can find a way to further improve it.

**Comment by johnbywater** [comment]
Interesting example. The trouble is that `B.Else` isn't a subclass of `B.Something`. That's why although `B.Scheduled` is a subclass of `B.Else`, `B.Scheduled` is not a subclass of `B.Something`.

Curiously, this structure works if the classes are processed with `dataclasses.dataclass` rather than inheriting from `pedantic.BaseModel`. That's because after dataclass has done its work, the `__bases__` of the processed class still has the origin of the generic alias, like it normally does if the super class isn't a parameterised generic class.

However Pydantic does something else. It creates a subclass for `Something[ExtendedShared]` and that's what appears in the `__bases__` of `Else`.

https://docs.pydantic.dev/latest/concepts/models/#generic-models

> Internally, Pydantic creates subclasses of the generic model at runtime when the generic model class is parametrized. These classes are cached, so there should be minimal overhead introduced by the use of generics models.

That is causing the `__bases__` of `Else` not to have `Something` but rather a subclass produced by Pydantic. This was breaking my strategy for identifying if a base class has been redefined by inspecting `__bases__` for the original classes.

I have two solutions.

1. I can avoid subclassing event classes that are not already subclasses of the standard base event class but which are generic classes, identified as having some `__parameters__`, and maybe prohibit such things being used directly as events objects in the aggregate, to preserve the design of having all events on an aggregate be subclasses of a base event class. That avoids dealing with the internals of Pydantic generics as a special case. But it means people can't use generic classes unless they ensure they are already subclasses of the aggregate's base event class.

2. Alternatively, when inspecting the `__bases__` of an event class that needs subclassing, I can look for and inspect the Pydantic attribute `__pydantic_generic_metadata__`, to identify if Pydantic has introduced an intermediate subclass, and if found then get the original base class from the `__bases__` of the Pydantic generated subclass. That creates a dependency on the particularities of Pydantic's internals which might change at any time. But it doesn't depend on importing Pydantic. It's just.a matter of dealing with dicts and strings.

https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel

> `__pydantic_generic_metadata__`  Metadata for generic models; contains data used for a similar purpose to args, origin, parameters in typing-module generics. May eventually be replaced by these.

I've implemented both, as alternatives, and they both make your test pass.

Which would you prefer? :-)

**Comment by johnbywater** [comment]
I went with option 2 6e5e8ea5222de0138bcca2390dba7d6f8010bf9f.

Let me know if https://pypi.org/project/eventsourcing/9.4.6/ works for you?

This test captures what you said today I think:
https://github.com/pyeventsourcing/eventsourcing/blob/63da84dbc4f857564fd85b38d4d00f054f52beda/tests/domain_tests/test_base_aggregate.py#L721

**Comment by bob-hoff** [comment]
Great, thanks this fixes it for me. And the test captures this well.
When looking for a solution to the problem myself, I came accross https://docs.python.org/3/library/types.html#types.get_original_bases

Maybe this is an option to simplify the code in the future.

**Comment by johnbywater** [comment]
Great news! I'm glad we fixed it!

I never considered generics for events classes before this week. It would be nice if nested classes could have parameters bound to the outer class arguments. That way we could have deeper reusable structures, and also the aggregate ID type argument of event classes on aggregates could be automatically paramerised by just providing a type argument to the aggregate class. But apparently that's not how it works...

The `get_original_bases()` function wouldn’t help with inspecting the base classes, I think, because it returns `__orig_bases__` if defined and otherwise `__bases__`. However, after Pydantic has subclassed the original generic alias, the original is in the `__bases__` of one of the `__bases__` of the event class being considered.

Usually the original (type arg erased) generic class object would be in `__bases__` and the original generic alias object (the thing with the type arguments appearing in the subclass definition) would be in `__orig_bases__`. So to match the generic class object we wouldn’t want to look at `__orig_bases__`.

All very confusing 😂
